version: "2"

linters:
  enable:
    - errcheck
    - gocritic
    - govet
    - staticcheck
    - unused

issues:
  exclude-rules:
    # Allow global vars in cmd/ (cobra pattern requires them)
    - path: cmd/
      linters:
        - gochecknoglobals
