version: 2

builds:
  - binary: sb
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/hpkotak/shellbud/cmd.version={{ .Version }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "sb_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  extra_files:
    - glob: extra/afm-bridge_*.tar.gz

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"

brews:
  - repository:
      owner: hpkotak
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    name: sb
    homepage: https://github.com/hpkotak/shellbud
    description: Context-aware shell assistant — interact with your shell in natural language
    license: MIT
    install: |
      bin.install "sb"
    extra_install: |
      on_macos do
        on_arm do
          resource("afm-bridge").stage { bin.install "afm-bridge" }
        end
      end
    custom_block: |
      on_macos do
        on_arm do
          resource "afm-bridge" do
            url "https://github.com/hpkotak/shellbud/releases/download/{{ .Tag }}/afm-bridge_{{ .Tag }}_darwin_arm64.tar.gz"
            sha256 "{{ .Env.BRIDGE_SHA256 }}"
          end
        end
      end
    test: |
      system bin/"sb", "--version"
